twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'  # Mantiene el estilo general
        - 'form/bootstrap_5_floating.html.twig'  # Sobrescribe solo lo necesario

when@test:
    twig:
        strict_variables: true
